main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('countries/', views.countries_index, name='countries_index'),
    path('countries/<int:country_id>/', views.countries_detail, name='country_detail'),
    path('trips/', views.trips_index, name='trips_index'),
    path('trips/<int:trip_id>/', views.trips_detail, name='trip_detail'),
    path('trips/create/', views.TripCreate.as_view(), name='trips_create'),
    path('trips/<int:pk>/update/', views.TripUpdate.as_view(), name='trips_update'),
    path('trips/<int:trip_id>/segment/<int:segment_id>/', views.assoc_segment, name='assoc_segment'),
    path('trips/<int:pk>/delete/', views.TripDelete.as_view(), name='trips_delete'),
    path('segments/', views.segments_index, name='segments_index'),
    path('segments/<int:segment_id>/', views.segments_detail, name='segment_detail'),
    # path('segments/create/', views.SegmentCreate.as_view(), name='segments_create'),
    path('trips/<int:trip_id>/add_segment/', views.add_segment, name='add_segment'),
    path('segments/<int:pk>/update/', views.SegmentUpdate.as_view(), name='segments_update'),
    path('segments/<int:pk>/delete/', views.SegmentDelete.as_view(), name='segments_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('fetchcountries', views.fetchCountries, name='fetch_countries')
]
# Not sure if the path(s) below are necessary any more:
# path('trips/<int:trip_id>/assoc_country/<int:country_id>/', views.assoc_country, name='assoc_country'),

tripcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

PURPOSES = (
    ('L', 'Leisure'),
    ('B', 'Business')
)

ROADTRIP = (
    ('Y', 'Yes'),
    ('N', 'No')
)

SEGMENT_TYPE = (
    ('J', 'Journey'),
    ('S', 'Stay'),
    ('A', 'Activity')
)

JOURNEY_TYPE = (
    ('A', 'By Air'),
    ('S', 'By Sea'),
    ('D', 'By Road'),
    ('L', 'By Rail'),
    ('O', 'Other')
)

DISTANCE_MEASUREMENT = (
    ('M', 'miles'),
    ('K', 'kilometres')
)

STAY_TYPE = (
    ('H', 'Hotel'),
    ('G', 'Guesthouse'),
    ('C', 'Campsite'),
    ('W', 'Wild Camping'),
    ('O', 'Other')
)

ACTIVITY_TYPE = (
    ('A', 'Active'),
    ('V', 'Adventurous'),
    ('C', 'Cultural'),
    ('S', 'Shopping'),
    ('E', 'Sightseeing'),
    ('H', 'Historical'),
    ('O', 'Other')
)

ORGANISER_TYPE = (
    ('S', 'Self-Organised'),
    ('T', 'Tour Operator'),
    ('G', 'Guide')
)

# Create your models here.
class Country(models.Model):
    name = models.CharField(max_length=100)
    continent = models.CharField(max_length=100)
    population = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('country_detail', kwargs={'country_id': self.id})
    
    class Meta:
        verbose_name_plural = "countries"


class Trip(models.Model):
    title = models.CharField(max_length=100)
    start = models.DateField('Start Date')
    end = models.DateField('End Date')
    highlight = models.TextField(max_length=250)
    roadtrip = models.CharField(
        max_length=1,
        choices=ROADTRIP,
        default=ROADTRIP[1][0]
    )
    purpose = models.CharField(        
        max_length=1,
        choices=PURPOSES,
        default=PURPOSES[0][0]
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title} on {self.start}"

    def get_absolute_url(self):
        return reverse('trip_detail', kwargs={'trip_id': self.id})

    class Meta:
        ordering = ['-start']


class Segment(models.Model):
    segment_type = models.CharField(
        choices=SEGMENT_TYPE,
        max_length=1,
    )
    start_date = models.DateField('Start Date')
    end_date = models.DateField('End Date')

    segment_country_start = models.ManyToManyField(
        Country,
        max_length=100,
    )
    
    # ------------ Journey ------------

    start_location = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    journey_type = models.CharField(
        choices=JOURNEY_TYPE,
        max_length=1,
        blank=True,
        null=True
    )

    distance_measurement = models.CharField(
        choices=DISTANCE_MEASUREMENT,
        max_length=1,
        blank=True,
        null=True
    )

    distance = models.IntegerField(
        blank=True,
        null=True
    )

    duration_hrs = models.IntegerField(
        blank=True,
        null=True
    )

    # ------------ Stay ------------

    stay_type = models.CharField(
        choices=STAY_TYPE,
        max_length=1,
        blank=True,
        null=True
    )
   
    stay_name = models.CharField(
        max_length=100,
        help_text="The name of the hotel, campsite, guesthouse or a description of your wild camping",
        blank=True,
        null=True
    )

    stay_location = models.CharField(
        max_length=100,
        help_text="Save the longitude and latitude to help yourself and others find your stay again!",
        blank=True,
        null=True
    )

    stay_map = models.CharField(
        max_length=300,
        help_text="Save a map link to help yourself and others find your stay again!",
        blank=True,
        null=True
    )
    
    # ------------ Activity ------------

    activity_type = models.CharField(
        choices=ACTIVITY_TYPE,
        max_length=1,
        blank=True,
        null=True
    )

    activity_description = models.TextField(
        max_length=300,
        blank=True,
        null=True
    )

    organiser_type = models.CharField(
        choices=ORGANISER_TYPE,
        max_length=1,
        blank=True,
        null=True
    )

    organiser_name = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    organiser_email = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    organiser_telephone = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )
    
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.segment_type} on {self.start_date}"
    

    def get_absolute_url(self):
        return reverse('segment_detail', kwargs={'segment_id': self.id})

main_app/forms.py
from django.forms import ModelForm
from .models import Segment

class SegmentForm(ModelForm):
  class Meta:
    model = Segment
    fields = ['segment_type', 'start_date', 'end_date', 'segment_country_start', 'start_location', 'journey_type', 'distance_measurement', 'distance', 'duration_hrs', 'stay_type', 'stay_name', 'stay_location', 'stay_map', 'activity_type', 'activity_description', 'organiser_type', 'organiser_name', 'organiser_email', 'organiser_telephone']

    

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Country, Trip, Segment

import requests

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import SegmentForm


# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

@login_required
def countries_index(request):
  countries = Country.objects.all()
  return render(request, 'countries/index.html', { 'countries': countries })

@login_required
def trips_index(request):
  trips = Trip.objects.filter(user=request.user)
  return render(request, 'trips/index.html', { 'trips': trips })

@login_required
def segments_index(request):
  segments = Segment.objects.filter(user=request.user)
  return render(request, 'segments/index.html', { 'segments': segments })

@login_required
def countries_detail(request, country_id):
  country = Country.objects.get(id=country_id)
  return render(request, 'countries/detail.html', { 
    'country': country,
  })

@login_required
def trips_detail(request, trip_id):
  trip = Trip.objects.get(id=trip_id)
  segments = Segment.objects.all()
  segment_form = SegmentForm()
  return render(request, 'trips/detail.html', { 
    'trip': trip,
    'segments': segments,
    'segment_form': segment_form
  })

@login_required
def segments_detail(request, segment_id):
  segment = Segment.objects.get(id=segment_id)
  return render(request, 'segments/detail.html', { 
    'segment': segment,
  })

class TripCreate(LoginRequiredMixin, CreateView):
  model = Trip
  fields = ['title', 'start', 'end', 'highlight', 'roadtrip', 'purpose']

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

@login_required
def add_segment(request, trip_id):
  form = SegmentForm(request.POST)
  if form.is_valid():
    new_segment = form.save(commit=False)
    new_segment.trip_id = trip_id
    new_segment.save()
  return redirect('trip_detail', trip_id=trip_id)

class TripUpdate(LoginRequiredMixin, UpdateView):
  model = Trip
  fields = '__all__'

class SegmentUpdate(LoginRequiredMixin, UpdateView):
  model = Segment
  fields = '__all__'

class TripDelete(LoginRequiredMixin, DeleteView):
  model = Trip
  success_url = '/trips'

class SegmentDelete(LoginRequiredMixin, DeleteView):
  model = Segment
  success_url = '/segments'

@login_required
def assoc_segment(request, trip_id, segment_id):
    Trip.objects.get(id=trip_id).segments.add(segment_id)
    return redirect('detail', trip_id=trip_id)

@login_required
def fetchCountries(request):
  try:
    response = requests.get("https://restcountries.com/v3.1/all").json()
    for r in response:
      if r['name']['common'] == "Antarctica":
        pass
      else:
        country = Country(
          name=r['name']['common'],
          continent=r['region'],
          population=r['population']
        )
        country.save()
  except Exception as e:
    print("An error occurred while fetching countries: ", e)
  return response


def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/trips/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Trip Details</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ trip.title }}</span>
        <p>Purpose: {{ trip.get_purpose_display }}</p>
        <p>Start: {{ trip.start }}</p>
        <p>End: {{ trip.end }}</p>
        <p>Highlight: {{ trip.highlight }}</p>
    </div>
    <div class="card-action">
        <a href="{% url 'trips_update' trip.id %}">Edit Trip</a>
        <a href="{% url 'trips_delete' trip.id %}">Delete Trip</a>
    </div>
</div>

<div>
    <h3>Trip Summary</h3>
    {% if trip.countries.count %}
        <table>    
            <tr>
                <th>Trip Detail</th>
                <th>#</th>
            </tr>
            <tr>
                <td>Countries Visited: </td>
                <td>{{ trip.countries.all.count }}</td>
            </tr>
            <tr>
                <td># Segments: </td>
                <td>{{ trip.segments_all_count }}</td>
            </tr>
        </table>
    {% else %}
        <p>No countries or cities listed in this trip! Add some below</p>
    {% endif %}
</div>
<br>

<h1>Segments of the {{ trip.title }}</h1>
  {% for segment in trip.segment_set.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ segment.get_segment_type_display }} Segment</span>
        <p>Country: {{ segment.segment_country_start.name }}</p>
        <p>Start Date: {{ segment.start_date }}</p>
          
          {% if segment.segment_type == "J" %}
            <p>End Date: {{ segment.end_date }}</p>
            <p>Start From: {{ segment.start_location }}</p>
            Travelled: {{ segment.get_journey_type_display }}</p>
            <p>Distance: {{ segment.distance }} {{ segment.get_distance_measurement_display }}</p>
            <p>Duration: {{ segment.duration }} hours</p>
          {% else %}
          {% endif %}
      </div>
    </div>  
  {% endfor %}
<br>

<div class="col s6">
  <h3>Add Segments to this Trip</h3>
  <form action="{% url 'add_segment' trip.id %}" method="POST">
    {% csrf_token %}
    <!-- Render the inputs -->
    {{ segment_form.as_p }}
    <input type="submit" class="btn" value="Add Segment">
  </form>
  
</div>
<br>

<script>
  const segmentTypeEl = document.getElementById('id_segment_type');
  M.FormSelect.init(segmentTypeEl);

  const startDateEl = document.getElementById('id_start_date');
  M.Datepicker.init(startDateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const endDateEl = document.getElementById('id_end_date');
  M.Datepicker.init(endDateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const segmentCountryStartEl = document.getElementById('id_segment_country_start');
  M.FormSelect.init(segmentCountryStartEl);
  
  const journeyTypeEl = document.getElementById('id_journey_type');
  M.FormSelect.init(journeyTypeEl);

  const distanceMeasurementEl = document.getElementById('id_distance_measurement');
  M.FormSelect.init(distanceMeasurementEl);

  const stayTypeEl = document.getElementById('id_stay_type');
  M.FormSelect.init(stayTypeEl);

  const activityTypeEl = document.getElementById('id_activity_type');
  M.FormSelect.init(activityTypeEl);

  const organiserTypeEl = document.getElementById('id_organiser_type');
  M.FormSelect.init(organiserTypeEl);

  const tripEl = document.getElementById('id_trip');
  M.FormSelect.init(tripEl);
</script>






{% endblock %}

main_app/templates/trips/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Trip List</h1>

{% for trip in trips %}
  <div class="card">
    <a href="{% url 'trip_detail' trip.id %}">
      <div class="card-content">
        <span class="card-title">{{ trip.title }}</span>
        <p>Purpose: {{ trip.get_purpose_display }}</p>
        <p>Start: {{ trip.start }}</p>
        <p>End: {{ trip.end }}</p>
        <p>Highlight: {{ trip.highlight }}</p>
      </div>
    </a>
  </div>
{% endfor %}
    
    
{% endblock %}